Repository YAPP-admin/yapp-web, pull requests merged in 2022-09, with the labels that each got.

#80 feat: 21기 지원 공고 오픈
  components/home/IntroSection/index.tsx
  components/recruit/RecruitField/RecruitDeveloper.tsx
  components/recruit/RecruitField/RecruitFieldExplain.tsx
  components/recruit/RecruitField/index.tsx
  constants/yapp.ts
  database/home.ts
  database/recruit.ts
  package.json
  public/assets/sponsors/sponsor1.png
  public/assets/sponsors/sponsor2.png
  public/assets/sponsors/sponsor3.png
  public/assets/sponsors/sponsor4.png
  public/assets/sponsors/sponsor5.png
  public/assets/sponsors/sponsor6.png
  public/assets/sponsors/sponsor7.png
  utils/getRecruitLink.ts
Labels: feature

#84 Feature/issue 83
  components/home/IntroSection/index.tsx
  database/home.ts
  database/recruit.ts
  database/sitemap.ts
  public/assets/images/og.png
  public/assets/project/20_thumbnail_weekand.png
Labels: feature

#90 feat: YAPP 메인 페이지 업데이트
  components/common/NewsCard/index.tsx
  components/home/IntroSection/index.tsx
  constants/breakpoints.ts
  database/home.ts
  database/recruit.ts
  pages/_app.tsx
  public/assets/fonts/Syne-ExtraBold.woff2
  public/assets/images/social1.png
  public/assets/images/social2.png
  public/assets/images/social3.png
  styles/fonts.ts
  styles/theme.ts
Labels: feature

#92 release: YAPP 메인 페이지 업데이트
  components/common/NewsCard/index.tsx
  components/home/IntroSection/index.tsx
  constants/breakpoints.ts
  database/home.ts
  database/recruit.ts
  pages/_app.tsx
  public/assets/fonts/Syne-ExtraBold.woff2
  public/assets/images/social1.png
  public/assets/images/social2.png
  public/assets/images/social3.png
  styles/fonts.ts
  styles/theme.ts
Labels: feature

#91 feat: 21기 운영진분들 잘 부탁드려요. 감사합니다. 🧡
  .github/auto_assign.yml
  README.md
Labels: refactor

#94 #93 feat: 후원사 업데이트
  database/home.ts
  public/assets/sponsors/sponsor1.png
  public/assets/sponsors/sponsor2.png
  public/assets/sponsors/sponsor3.png
  public/assets/sponsors/sponsor4.png
Labels: feature

#95 release: 후원사 업데이트
  .github/auto_assign.yml
  README.md
  database/home.ts
  public/assets/sponsors/sponsor1.png
  public/assets/sponsors/sponsor2.png
  public/assets/sponsors/sponsor3.png
  public/assets/sponsors/sponsor4.png
Labels: release

#97 hotfix: jpub(제이펍) 후원사로 부터 받은 로고로 변경
  database/home.ts
  public/assets/sponsors/sponsor1.png
Labels: hotfix, release

#99 feat: 카카오헤어샵 후원사 추가 업데이트
  database/home.ts
  public/assets/sponsors/sponsor0.png
  public/assets/sponsors/sponsor1.png
Labels: feature

#100 release: 카카오헤어샵 후원사 추가 업데이트
  database/home.ts
  public/assets/sponsors/sponsor0.png
Labels: release

#103 release: 21기 지원 마감
  components/home/IntroSection/index.tsx
  components/recruit/RecruitBanner/index.tsx
  components/recruit/RecruitField/RecruitFieldExplain.tsx
  database/recruit.ts
  yarn.lock
Labels: release
