Repository YAPP-admin/yapp-web, pull requests merged in 2022-02, with the labels that each got.

#2 feat: 디자인 시스템 초기 구성
  components/.keep
  components/Button.tsx
  components/index.ts
  pages/_app.tsx
  pages/index.tsx
  styles/global-styles.ts
  styles/media.ts
  styles/styled.d.ts
  styles/theme.ts
Labels: feature

#3 Feat: Box 컴포넌트
  components/Box.tsx
  components/Button.tsx
  components/index.ts
  pages/index.tsx
  styles/theme.ts
Labels: question, feature

#6 feat: Footer 컴포넌트 구현
  components/Footer.tsx
  components/index.ts
  constants/yapp.ts
  pages/index.tsx
  styles/theme.ts
Labels: feature

#5 fix: Box 컴포넌트 상속 안받아지는 오류 해결
  components/Box.tsx
Labels: bug

#11 feat: Home Page 구현
  components/Button.tsx
  components/Carousel/index.tsx
  components/FloatingButton/index.tsx
  components/Home/Main.tsx
  components/LayoutWrapper.tsx
  components/SEO.tsx
  components/index.ts
  constants/yapp.ts
  database/.keep
  database/home.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  styles/global-styles.ts
  styles/media.ts
  styles/theme.ts
  tsconfig.json
  yarn.lock
Labels: feature

#13 feat: Recruit 페이지
  components/Box.tsx
  components/Button.tsx
  components/Footer/index.tsx
  components/Header/index.tsx
  components/RecruitLayout/index.tsx
  components/index.ts
  constants/breakpoints.ts
  database/recruit.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/recruit/components/ApplyWay/index.tsx
  pages/recruit/components/Enquiry/index.tsx
  pages/recruit/components/FrequentlyAskedQuestions/index.tsx
  pages/recruit/components/RecruitBanner/index.tsx
  pages/recruit/components/RecruitField/RecruitDesigner.tsx
  pages/recruit/components/RecruitField/RecruitDeveloper.tsx
  pages/recruit/components/RecruitField/RecruitFieldExplain.tsx
  pages/recruit/components/RecruitField/RecruitProjectManager.tsx
  pages/recruit/components/RecruitField/index.tsx
  pages/recruit/components/RecruitSchedule/index.tsx
  pages/recruit/components/SectionTemplate/index.tsx
  pages/recruit/components/SectionTitle/index.tsx
  pages/recruit/components/index.ts
  pages/recruit/index.tsx
  public/assets/icons/arrow_down.svg
  styles/media.ts
  styles/styled.d.ts
  styles/theme.ts
  utils/.keep
  utils/getDeveloperFieldExplain.ts
  yarn.lock
Labels: feature

#14 feat: Home 화면 구현 및 Storybook CI 구성
  .babelrc
  .eslintrc.json
  .github/workflows/Storybook-CI.yml
  .storybook/main.js
  .storybook/preview.js
  components/Button/index.stories.tsx
  components/Button/index.tsx
  components/Carousel/index.stories.tsx
  components/Carousel/index.tsx
  components/FloatingButton/index.stories.tsx
  components/FloatingButton/index.tsx
  components/index.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/components/LandingMain.tsx
  pages/index.stories.tsx
  pages/index.tsx
  public/assets/icons/contact.svg
  public/assets/icons/facebook.svg
  public/assets/icons/kakao.svg
  public/assets/icons/mail.svg
  styles/global-styles.ts
  styles/theme.ts
  yarn.lock
Labels: feature, enviroment

#15 feat: 디자인 시스템 추가 (색상, letter-spacing)
  styles/theme.ts
Labels: feature

#18 feat: 홈 (랜딩) 페이지 구현 / Text Animation 제외
  components/AnimatedBox/index.stories.tsx
  components/AnimatedBox/index.tsx
  components/Box.tsx
  components/Button/index.stories.tsx
  components/Carousel/index.tsx
  components/FloatingButton/index.tsx
  components/LayoutWrapper.tsx
  components/NewsCard/index.stories.tsx
  components/NewsCard/index.tsx
  components/index.ts
  constants/yapp.ts
  database/home.ts
  database/recruit.ts
  package.json
  pages/_app.tsx
  pages/components/AnimatedTextSection/index.tsx
  pages/components/GridSection/index.tsx
  pages/components/IntroSection/index.tsx
  pages/components/NewsSection/index.tsx
  pages/components/ProjectSection/index.tsx
  pages/components/SectionTemplate/index.tsx
  pages/components/SectionTitle/index.tsx
  pages/components/SponsorSection/index.tsx
  pages/components/index.ts
  pages/index.stories.tsx
  pages/index.tsx
  pages/recruit/components/ApplyWay/index.tsx
  pages/recruit/components/FrequentlyAskedQuestions/index.tsx
  pages/recruit/components/RecruitBanner/index.tsx
  pages/recruit/components/RecruitField/RecruitFieldExplain.tsx
  pages/recruit/components/RecruitField/index.tsx
  pages/recruit/components/RecruitSchedule/index.tsx
  public/assets/icons/arrow_left.svg
  public/assets/icons/arrow_right.svg
  public/assets/icons/contact.svg
  public/assets/icons/index.ts
  public/assets/icons/mail.svg
  public/assets/icons/plus.svg
  public/assets/images/facebook1.png
  public/assets/images/facebook2.png
  public/assets/images/facebook3.png
  public/assets/images/naverD2.png
  public/assets/images/project1.png
  public/assets/images/project2.png
  public/assets/images/project3.png
  styles/global-styles.ts
  styles/theme.ts
  yarn.lock
Labels: feature
