Repository YAPP-admin/yapp-web, pull requests merged in 2023-04, with the labels that each got.

#124 fix: 22기 지원기간 수정
  database/recruit.ts
Labels: hotfix

#127 Hotfix: 서류 접수 기간 요일 수정
  database/recruit.ts
Labels: hotfix, release

#129 Hotfix: 따끈한 최근 소식 22기 포스트 지원 기간 수정
  database/home.ts
  public/assets/images/social1.png
Labels: hotfix, release

#134 feat: 21기 프로젝트 오타 수정
  database/home.ts
  database/projects/21th/artie.json
  database/projects/21th/buddycon.json
  database/projects/21th/findthings.json
  database/projects/21th/thumbsup.json
  database/projects/21th/tmtm.json
Labels: feature

#135 release: 21기 프로젝트 업데이트
  database/home.ts
  database/projects/21th/artie.json
  database/projects/21th/buddycon.json
  database/projects/21th/findthings.json
  database/projects/21th/thumbsup.json
  database/projects/21th/tmtm.json
Labels: release

#138 release: 22기 지원마감
  components/recruit/RecruitField/RecruitFieldExplain.tsx
  database/recruit.ts
Labels: release

#140 feat: 22기 운영진분들 잘 부탁드려요. 🧡
  .github/auto_assign.yml
Labels: documentation

#141 fix(thismeme.json): thismeme 링크 수정
  database/projects/21th/thismeme.json
Labels: feature

#142 release(thismeme.json): thismeme 링크 수정 후 배포
  .github/auto_assign.yml
  database/projects/21th/thismeme.json
Labels: release
